name: Installing Python

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14, windows-latest]
        py-version: [3.10, 3.11, 3.12]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        if: matrix.os != 'macos-14'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py-version }}

      - name: Show Python version
        if: matrix.os != 'macos-14'
        run: python --version
